---
 - name: to deploy code to apache web server
   copy:
    src: files/index.html
    dest: /var/www/html/index.html
   notify:
    - restart apache

 - name: to deploy code to apache web server
   copy:
    src: files/httpd.conf
    dest: /var/www/html/httpd.conf
   notify:
    -  restart apche

# - name: to restart the server after code deployment
 #  service:
  #  name: "{{ package }}"
   # state: restarted

